stages:
  - build
  - publish
  - deploy
  - cleanup

image: docker-registry.prozorro.gov.ua/cdb/openprocurement.api/ci

variables:
  IMAGE: "medicines:$CI_COMMIT_SHORT_SHA"
  IMAGE_TEST: "medicines:$CI_COMMIT_SHORT_SHA-test"

build-new-image:
  stage: build
  tags:
    - shell
  script:
    - make docker-build

push-latest-image:
  stage: publish
  tags:
    - shell
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker tag $IMAGE $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

push-tagged-image:
  stage: publish
  tags:
    - shell
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker tag $IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - tags

review:
  stage: deploy
  tags:
    - shell
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: start
    url: http://api.${CI_COMMIT_REF_SLUG}.${K8S_DOMAIN}/api/1.0/registry
    on_stop: stop_review
    auto_stop_in: 1 month
  variables:
    TAG: $CI_COMMIT_REF_SLUG
  script:
    - make dev-auth-secret
    - make dev-config-secret
    - make dev-update
  when: manual
  only:
    - master


stop_review:
  stage: deploy
  script:
    - make dev-auth-secret
    - make dev-config-secret-delete
    - make dev-auth-secret-delete
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: stop
  tags:
    - shell
  when: manual
  only:
    - master


clenup-test-image:
  stage: cleanup
  tags:
    - shell
  script:
    - docker rmi -f $IMAGE || true
    - docker rmi -f $IMAGE_TEST || true
  when: always
