apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prozorro.medicines.fullname" . }}
  labels:
{{ include "prozorro.medicines.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prozorro.medicines.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ include "prozorro.medicines.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "prozorro.medicines.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ include "prozorro.medicines.name" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ include "prozorro.medicines.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["python", "-m", "prozorro.medicines.api"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.1"
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-medicines-secret
          livenessProbe:
            httpGet:
              path: /api/1.0/ping
              port: http
          readinessProbe:
            httpGet:
              path: /api/1.0/ping
              port: http
  