
mongodb:
  image:
    tag: 4.4
  replicas: 1
  persistentVolume:
    enabled: false
    size: 129M

replicaCount: 1

image:
  repository: docker-registry.prozorro.gov.ua/cdb/prozorro-medicines
  tag: latest
  pullPolicy: Always

cronjob:
  schedule: "0 5 * * *"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      nginx.ingress.kubernetes.io/limit-rps: "1"
  hosts:
    - host: medicines.latest.k8s.prozorro.gov.ua
      paths:
        - path: /
          service: api
  tls: []

imagePullSecrets:
  - name: registry-gitlab

nameOverride: ""
fullnameOverride: ""
